services:
  ezbookkeeping:
    build: .
    image: ezbookkeeping
    container_name: ezbookkeeping
    ports:
      - "8080:8080"
    volumes:
      - moneymanager:/ezbookkeeping/data
      - ./log:/ezbookkeeping/log
      - ./storage:/ezbookkeeping/storage
      - ./conf:/ezbookkeeping/conf
    restart: unless-stopped
    environment:
      - EBK_SERVER_DOMAIN=192.168.1.8
    #   - EBK_DB_DSN=...

volumes:
  moneymanager:
    external: true
